/* ==========================================================
   BANK SOALAN SEJARAH KERTAS 1 (1249/1)
   Digunakan bersama oleh index.html dan analisis.html
   Disediakan oleh Cikgu Muhammad Rabbani, SMK Dato' Undang Musa Al-Haj
   ========================================================== */
/* =========================================================
   BANK SOALAN
   j    = kunci jawapan
   klu  = petunjuk sebelum menjawab
   betul= sebab jawapan itu betul
   salah= sebab setiap pilihan lain salah
   ========================================================= */
const BANK = {
mrsm:{
  nama:"Percubaan SPM MRSM 2024",
  kod:"1249/1 &middot; Oktober 2024",
  perincian:"40 soalan objektif. Skema rasmi Bahagian Pendidikan Menengah MARA, lengkap dengan aras kesukaran (R / S / T).",
  soalan:[
  {n:1,tk:"T4",ms:"7",aras:"R",bab:"Kesultanan Melayu Melaka",
   s:"Maklumat berikut merujuk kepada alat kebesaran diraja pada zaman Kesultanan Melayu Melaka.",
   stim:"\u2022 Nobat\n\u2022 Cap mohor",
   p:{A:"Menggambarkan kemewahan kerajaan",B:"Mengesahkan keturunan pemerintah",C:"Mempamerkan keunikan kesenian",D:"Menunjukkan simbol kedaulatan"},
   j:"D",
   klu:"Fikirkan fungsi alat kebesaran: siapa sahaja yang boleh menggunakannya dan apa yang diisytiharkan kepada rakyat serta kerajaan luar?",
   betul:"Nobat dan cap mohor ialah alat kebesaran yang hanya boleh digunakan oleh sultan. Kedua-duanya menjadi lambang kekuasaan tertinggi dan kedaulatan sultan sebagai pemerintah yang sah.",
   salah:{A:"Alat kebesaran bukan diukur dari segi nilai kemewahan tetapi dari segi kuasa yang disimbolkannya.",B:"Keturunan pemerintah disahkan melalui salasilah dan adat pertabalan, bukan melalui nobat atau cap mohor.",C:"Unsur seni memang ada, tetapi itu bukan tujuan utama alat kebesaran diraja diwujudkan."}},

  {n:2,tk:"T4",ms:"9",aras:"R",bab:"Kesultanan Melayu Melaka",
   s:"Apakah sumber pendapatan Kesultanan Melayu Melaka?",
   stim:"I  Hasil perdagangan\nII  Ufti wilayah\nIII  Pajakan tanah\nIV  Sumber galian",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   j:"A",
   klu:"Melaka ialah sebuah empayar maritim, bukan negeri pertanian atau perlombongan. Apakah dua sumber yang paling sinonim dengan pelabuhan dan wilayah takluk?",
   betul:"Cukai dan hasil perdagangan di pelabuhan Melaka menjadi sumber pendapatan utama, ditambah dengan ufti (bunga emas dan hasil bumi) yang dihantar oleh wilayah naungan sebagai tanda taat setia.",
   salah:{B:"Sumber galian bukan tunjang ekonomi Melaka; kekuatannya terletak pada pelabuhan entrepot.",C:"Pajakan tanah merupakan amalan pentadbiran zaman kemudian, bukan sumber pendapatan Melaka.",D:"Kedua-dua pajakan tanah dan sumber galian tidak menjadi sumber pendapatan utama kerajaan Melaka."}},

  {n:3,tk:"T4",ms:"24-25",aras:"S",bab:"Nasionalisme di Eropah",
   s:"Maklumat berikut berkaitan dengan perkembangan nasionalisme di Eropah. Apakah isu yang diperjuangkan dalam revolusi tersebut?",
   stim:"\u2022 Revolusi Keagungan (1688)\n\u2022 Revolusi Perancis (1789)",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   pilihanTambahan:"I  Kebebasan hak asasi\nII  Keunggulan suara rakyat\nIII  Penggabungan tanah jajahan\nIV  Diskriminasi penjajah",
   klu:"Kedua-dua revolusi ini berlaku di dalam negara sendiri, bukan menentang kuasa asing. Apakah yang dituntut rakyat daripada raja mereka?",
   j:"A",
   betul:"Revolusi Keagungan dan Revolusi Perancis menuntut kebebasan hak asasi rakyat dan mengangkat prinsip kedaulatan rakyat, iaitu suara rakyat mengatasi kuasa mutlak raja.",
   salah:{B:"Diskriminasi penjajah tidak berkaitan kerana kedua-dua revolusi berlaku dalam negara sendiri, bukan di tanah jajahan.",C:"Penggabungan tanah jajahan ialah ciri imperialisme, bukan tuntutan revolusi rakyat.",D:"Kedua-dua isu ini tiada kaitan dengan tuntutan hak rakyat dalam revolusi tersebut."}},

  {n:4,tk:"T4",ms:"43",aras:"R",bab:"Tokoh nasionalisme",
   s:"Tokoh berikut memberi sumbangan besar kepada kesedaran nasionalisme di Tanah Melayu pada abad ke-20. Apakah sumbangan beliau?",
   stim:"[Gambar: Ibu Zain (Zainun Sulaiman)]",
   p:{A:"Menuntut peluang dalam perkhidmatan kerajaan",B:"Memberi kesedaran kepentingan pendidikan",C:"Menubuhkan persatuan sosioekonomi",D:"Memartabatkan kesenian bangsa"},
   j:"B",
   klu:"Ibu Zain seorang guru lulusan Maktab Perguruan Perempuan Melayu Melaka. Bidang mana yang paling rapat dengan kerjaya dan perjuangannya?",
   betul:"Ibu Zain memperjuangkan pendidikan, khususnya pendidikan untuk kaum wanita, sebagai jalan membebaskan bangsa daripada kemunduran. Beliau menulis, mengajar dan menganjurkan persidangan kesedaran.",
   salah:{A:"Tuntutan peluang dalam perkhidmatan kerajaan lebih dikaitkan dengan kesatuan kaum guru dan pegawai, bukan perjuangan Ibu Zain.",C:"Beliau aktif dalam persatuan kaum ibu, namun tumpuannya ialah pendidikan, bukan program sosioekonomi.",D:"Kesenian bangsa bukan bidang perjuangan utama Ibu Zain."}},

  {n:5,tk:"T4",ms:"58-59",aras:"R",bab:"Perang Dunia Kedua",
   s:"Apakah faktor yang mencetuskan Perang Dunia Kedua antara tahun 1939-1945?",
   p:{A:"Pembunuhan pewaris takhta Austria-Hungary",B:"Pencerobohan terhadap Belgium",C:"Kemunculan ideologi Fasisme",D:"Krisis di rantau Balkan"},
   j:"C",
   klu:"Tiga daripada pilihan ini ialah sebab Perang Dunia Pertama. Cari satu sahaja yang muncul pada tahun 1930-an.",
   betul:"Kemunculan ideologi Fasisme di Itali dan Nazisme di Jerman melahirkan dasar perluasan kuasa yang agresif sehingga mencetuskan Perang Dunia Kedua.",
   salah:{A:"Pembunuhan Archduke Franz Ferdinand ialah pencetus Perang Dunia Pertama pada tahun 1914.",B:"Pencerobohan Belgium berlaku dalam Perang Dunia Pertama.",D:"Krisis Balkan ialah punca ketegangan sebelum Perang Dunia Pertama."}},

  {n:6,tk:"T4",ms:"64-68",aras:"R",bab:"Pendudukan Jepun",
   s:"Mengapakah Jepun ingin menguasai Asia Tenggara pada abad ke-20?",
   p:{A:"Mendapatkan tenaga buruh",B:"Memperoleh bahan mentah",C:"Menyebar fahaman agama",D:"Mengukuhkan nilai mata wang"},
   j:"B",
   klu:"Jepun sebuah negara perindustrian yang miskin sumber alam. Apa yang paling diperlukan oleh kilang dan tenteranya?",
   betul:"Perindustrian dan ketenteraan Jepun memerlukan bahan mentah seperti bijih timah, getah dan minyak yang banyak terdapat di Asia Tenggara.",
   salah:{A:"Tenaga buruh diperoleh selepas pendudukan, bukan matlamat asal dasar perluasan kuasa Jepun.",C:"Jepun tidak menjadikan penyebaran agama sebagai tujuan perluasan kuasa.",D:"Nilai mata wang bukan matlamat pencerobohan; malah Jepun memperkenalkan wang pisang yang tidak bernilai."}},

  {n:7,tk:"T4",ms:"106",aras:"R",bab:"Malayan Union",
   s:"United Malays National Organisation (UMNO) ditubuhkan pada 11 Mei 1946 untuk menentang Malayan Union. Apakah tindakan yang dilakukan oleh pertubuhan tersebut?",
   p:{A:"Menganjur bantahan besar-besaran",B:"Meletak jawatan beramai-ramai",C:"Membawa kes ke mahkamah",D:"Menutup premis perniagaan"},
   j:"A",
   klu:"Ingat gambar orang Melayu berkain hitam berhimpun di luar bangunan pentadbiran ketika pelantikan Gabenor Malayan Union.",
   betul:"UMNO menganjurkan bantahan besar-besaran secara damai seperti demonstrasi, perarakan, memakai kain hitam dan memulaukan istiadat pelantikan Gabenor Sir Edward Gent.",
   salah:{B:"Peletakan jawatan beramai-ramai bukan strategi UMNO menentang Malayan Union.",C:"Penentangan dibuat melalui tekanan politik dan rundingan, bukan melalui mahkamah.",D:"Penutupan premis perniagaan bukan kaedah penentangan yang digunakan."}},

  {n:8,tk:"T4",ms:"109",aras:"R",bab:"Penyerahan Sarawak",
   s:"Rakyat tempatan menentang penyerahan Sarawak pada tahun 1946 kerana British",
   p:{A:"menghalang pemilikan tanah peribumi",B:"menindas kegiatan berpersatuan",C:"menafikan hak berkerajaan sendiri",D:"menghadkan peluang dalam pentadbiran"},
   j:"C",
   klu:"Penyerahan itu bercanggah dengan janji dalam Perlembagaan Sarawak 1941. Apakah yang dijanjikan kepada rakyat dalam perlembagaan tersebut?",
   betul:"Penyerahan Sarawak kepada British menafikan hak rakyat untuk berkerajaan sendiri sebagaimana yang dijanjikan dalam Perlembagaan Sarawak 1941, lalu mencetuskan gerakan antipenyerahan.",
   salah:{A:"Isu pemilikan tanah bukan punca utama gerakan antipenyerahan.",B:"Persatuan seperti Persatuan Kebangsaan Melayu Sarawak masih bergerak aktif menentang penyerahan.",D:"Peluang dalam pentadbiran ialah kesan sampingan, bukan sebab utama penentangan."}},

  {n:9,tk:"T4",ms:"114-115",aras:"R",bab:"Penyerahan Sabah",
   s:"Mengapakah Syarikat Borneo Utara British (SBUB) menyerahkan Sabah kepada kerajaan British pada tahun 1946?",
   p:{A:"Penamatan tempoh konsesi",B:"Kemusnahan bandar akibat perang",C:"Pemberontakan tokoh masyarakat",D:"Desakan penduduk tempatan"},
   j:"B",
   klu:"Kesan Perang Dunia Kedua di Sandakan dan Jesselton amat teruk. Adakah sebuah syarikat perniagaan mampu menanggung kos pembinaan semula?",
   betul:"Bandar utama seperti Sandakan dan Jesselton musnah akibat pengeboman Perang Dunia Kedua. SBUB tidak mampu menanggung kos pembinaan semula lalu menyerahkan Sabah kepada British. <i>(Nota: skema asal MRSM mencatat D, tetapi terdapat pembetulan tulisan tangan kepada B yang menepati fakta buku teks.)</i>",
   salah:{A:"Konsesi SBUB tidak tamat pada tahun 1946; penyerahan berlaku atas desakan kewangan.",C:"Penentangan tokoh tempatan berlaku selepas penyerahan, bukan puncanya.",D:"Penduduk tempatan tidak mendesak penyerahan, malah ramai membantahnya."}},

  {n:10,tk:"T4",ms:"128",aras:"S",bab:"Nasionalis radikal",
   s:"Golongan nasionalis Melayu radikal diketepikan daripada menyertai mesyuarat Jawatankuasa Kerja pada tahun 1946. Apakah tindakan golongan nasionalis Melayu radikal terhadap situasi tersebut?",
   p:{A:"Membentuk Pusat Tenaga Rakyat",B:"Menganjurkan demonstrasi aman",C:"Mengadakan persidangan kebangsaan",D:"Menubuhkan Dewan Perundangan Negeri"},
   j:"A",
   klu:"Golongan radikal mencari gabungan lain untuk bersuara. Apakah nama gabungan yang kemudiannya bekerjasama dengan AMCJA?",
   betul:"Golongan radikal membentuk Pusat Tenaga Rakyat (PUTERA) sebagai gabungan menyuarakan pandangan mereka, lalu bekerjasama dengan AMCJA menghasilkan Perlembagaan Rakyat.",
   salah:{B:"Demonstrasi aman ialah kaedah UMNO menentang Malayan Union, bukan tindakan khusus golongan radikal ketika itu.",C:"Persidangan kebangsaan bukan tindakan yang diambil selepas mereka diketepikan.",D:"Dewan Perundangan Negeri ditubuhkan oleh British, bukan oleh golongan radikal."}},

  {n:11,tk:"T4",ms:"137",aras:"T",bab:"CLC",
   s:"Persekutuan Tanah Melayu 1948 merintis kepada penubuhan Jawatankuasa Hubungan Antara Kaum (CLC). Apakah kepentingan penubuhan jawatankuasa tersebut?",
   p:{A:"Penyeragaman pentadbiran",B:"Persefahaman pemimpin",C:"Kesedaran berpolitik",D:"Kerjasama antara persatuan"},
   j:"B",
   klu:"CLC ialah wadah pemimpin pelbagai kaum berbincang secara tertutup. Apakah hasil paling penting daripada perbincangan sedemikian?",
   betul:"CLC menjadi platform pemimpin pelbagai kaum bertemu dan berunding sehingga lahir tolak ansur serta persefahaman yang menjadi asas perpaduan dan kemerdekaan.",
   salah:{A:"Penyeragaman pentadbiran ialah kesan Persekutuan Tanah Melayu 1948, bukan peranan CLC.",C:"Kesedaran berpolitik sudah wujud sebelum CLC ditubuhkan.",D:"CLC menghimpunkan pemimpin, bukan menggabungkan persatuan sebagai badan."}},

  {n:12,tk:"T4",ms:"154-155",aras:"R",bab:"Darurat",
   s:"Maklumat berikut merujuk kepada pasukan keselamatan yang terlibat dalam menangani ancaman komunis di negara kita. Apakah peranan pasukan tersebut?",
   stim:"\u2022 Senoi Praaq (Urang Perang)\n\u2022 Sarawak Rangers",
   p:{A:"Membawa bekalan makanan",B:"Melindungi pekerja lombong",C:"Mempertahankan kawasan bandar",D:"Mengesan tempat persembunyian musuh"},
   j:"D",
   klu:"Kedua-dua pasukan ini terdiri daripada anak peribumi yang amat mahir membaca tanda di dalam hutan tebal.",
   betul:"Senoi Praaq dan Sarawak Rangers mahir menjejak dalam hutan, lalu digunakan untuk mengesan laluan dan tempat persembunyian pengganas komunis.",
   salah:{A:"Bekalan makanan dikawal melalui Sistem Kawalan Makanan (Operasi Starvation), bukan tugas pasukan penjejak.",B:"Perlindungan lombong dan estet dilakukan oleh Special Constables.",C:"Pertahanan bandar bukan kekuatan pasukan yang mahir dalam hutan."}},

  {n:13,tk:"T4",ms:"161",aras:"T",bab:"Darurat",
   s:"Apakah kesan zaman darurat dari tahun 1948 hingga 1960 terhadap negara kita?",
   p:{A:"Merapatkan jurang sosioekonomi",B:"Mempercepat kemerdekaan",C:"Menetapkan persempadanan semula",D:"Memajukan perkhidmatan pengangkutan"},
   j:"B",
   klu:"British perlu menunjukkan bahawa penduduk tempatan menyokong kerajaan dan bukan komunis. Bagaimana cara terbaik membuktikannya?",
   betul:"Bagi memenangi hati rakyat dan melemahkan pengaruh komunis, British mempercepat proses pemberian kuasa kepada penduduk tempatan sehingga mempercepat kemerdekaan.",
   salah:{A:"Jurang sosioekonomi masih ketara selepas darurat, malah menjadi isu utama sehingga tahun 1970-an.",C:"Persempadanan semula tidak berlaku akibat darurat.",D:"Pengangkutan tidak menjadi kesan utama; tumpuan darurat ialah keselamatan dan politik."}},

  {n:14,tk:"T4",ms:"172",aras:"T",bab:"Idea negara merdeka",
   s:"Tokoh berikut telah mengemukakan idea pembentukan negara merdeka. Apakah idea tokoh tersebut?",
   stim:"\u2022 Ibrahim Haji Yaakob\n\u2022 Ahmad Boestamam",
   p:{A:"Penyatuan bangsa Melayu",B:"Penggabungan wilayah baharu",C:"Penubuhan sebuah negara Islam",D:"Pergerakan politik bersifat sederhana"},
   j:"A",
   klu:"Kedua-dua tokoh ini golongan radikal berhaluan kiri yang terpengaruh dengan gagasan Melayu Raya atau Indonesia Raya.",
   betul:"Ibrahim Haji Yaakob dan Ahmad Boestamam memperjuangkan penyatuan bangsa Melayu menerusi gagasan Melayu Raya sebagai asas pembentukan negara merdeka.",
   salah:{B:"Penggabungan wilayah baharu ialah idea Gagasan Malaysia pada tahun 1961, bukan idea kedua-dua tokoh ini.",C:"Perjuangan negara Islam lebih dikaitkan dengan Hizbul Muslimin.",D:"Kedua-duanya tergolong dalam kumpulan radikal, bukan sederhana."}},

  {n:15,tk:"T4",ms:"176-177",aras:"S",bab:"RIDA / CLC",
   s:"Maklumat berikut berkaitan agensi yang ditubuhkan di negara kita pada tahun 1950. Apakah perkara yang menjadi tolak ansur orang Melayu sehingga membawa kepada penubuhan agensi tersebut?",
   stim:"Lembaga Pembangunan Industri Desa (RIDA) ditubuhkan hasil persetujuan dalam Jawatankuasa Hubungan Antara Kaum (CLC).",
   p:{A:"Pilihan raya",B:"Kewarganegaraan",C:"Sukatan pelajaran",D:"Perkhidmatan awam"},
   j:"B",
   klu:"Dalam CLC berlaku pertukaran: orang Melayu melonggarkan satu syarat penting, dan sebagai balasan ekonomi luar bandar dibangunkan.",
   betul:"Orang Melayu bersetuju melonggarkan syarat kewarganegaraan kepada kaum lain, dan sebagai tolak ansur British menubuhkan RIDA untuk membangunkan ekonomi orang Melayu di luar bandar.",
   salah:{A:"Pilihan raya bukan isu tolak ansur yang membawa kepada penubuhan RIDA.",C:"Sukatan pelajaran ialah isu Penyata Razak 1956, bukan asas penubuhan RIDA.",D:"Perkhidmatan awam tidak menjadi isu tolak ansur dalam CLC."}},

  {n:16,tk:"T4",ms:"200",aras:"R",bab:"Pilihan raya 1955",
   s:"Apakah syarat menjadi calon dalam Pilihan Raya Majlis Perundangan Persekutuan 1955?",
   stim:"I  Mewakili parti tertentu\nII  Berumur 21 tahun\nIII  Berstatus warganegara\nIV  Mendapat pendidikan tinggi",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   j:"C",
   klu:"Calon bebas juga dibenarkan bertanding. Jadi syarat mana yang benar-benar wajib?",
   betul:"Syarat calon ialah berumur sekurang-kurangnya 21 tahun dan berstatus warganegara Persekutuan Tanah Melayu.",
   salah:{A:"Calon tidak wajib mewakili parti kerana calon bebas dibenarkan bertanding.",B:"Pendidikan tinggi bukan syarat menjadi calon.",D:"Pendidikan tinggi tidak pernah menjadi syarat pencalonan."}},

  {n:17,tk:"T4",ms:"202",aras:"T",bab:"Pilihan raya 1955",
   s:"Jadual berikut berkaitan keputusan Pilihan Raya Umum 1955. Mengapakah Parti Perikatan memenangi pilihan raya tersebut?",
   stim:"Perikatan  \u2014  52 calon  \u2014  51 kerusi\nParti Negara  \u2014  30 calon  \u2014  0 kerusi\nParti Islam Se-Tanah Melayu  \u2014  11 calon  \u2014  1 kerusi",
   p:{A:"Memperjuangkan sistem monarki",B:"Meminda undang-undang barat",C:"Menjalin kerjasama politik",D:"Mendaftarkan calon lebih awal"},
   j:"C",
   klu:"Bandingkan Perikatan dengan Parti Negara: apakah kelebihan struktur parti yang menggabungkan UMNO, MCA dan MIC?",
   betul:"Perikatan menang besar kerana kerjasama politik antara UMNO, MCA dan MIC berjaya menarik sokongan pengundi daripada semua kaum.",
   salah:{A:"Sistem monarki bukan isu yang menentukan kemenangan pilihan raya.",B:"Pindaan undang-undang barat bukan manifesto yang memenangi pengundi.",D:"Pendaftaran awal calon tidak memberi kelebihan kemenangan."}},

  {n:18,tk:"T4",ms:"221",aras:"S",bab:"Suruhanjaya Reid",
   s:"Suruhanjaya Reid ditubuhkan untuk merangka Perlembagaan Persekutuan Tanah Melayu 1957. Bagaimanakah tugas tersebut dilaksanakan?",
   p:{A:"Menganjurkan kongres",B:"Melaksanakan pungutan suara",C:"Mengadakan persidangan akhbar",D:"Mengumpul pandangan pelbagai pihak"},
   j:"D",
   klu:"Suruhanjaya ini menerima lebih 100 memorandum daripada pelbagai pihak. Apakah kaedah kerja yang ditunjukkan?",
   betul:"Suruhanjaya Reid mengadakan perbicaraan awam dan menerima memorandum daripada raja-raja, parti politik, pertubuhan dan orang perseorangan sebelum merangka draf perlembagaan.",
   salah:{A:"Kongres bukan kaedah kerja suruhanjaya.",B:"Tiada pungutan suara diadakan untuk merangka perlembagaan.",C:"Persidangan akhbar bukan kaedah mengumpul pandangan rakyat."}},

  {n:19,tk:"T4",ms:"222",aras:"S",bab:"Draf Perlembagaan 1956",
   s:"Maklumat berikut berkaitan kandungan draf perlembagaan negara yang dikemukakan oleh Suruhanjaya Perlembagaan Persekutuan Tanah Melayu pada 1956. Apakah X?",
   stim:"\u2022 Konsep Raja Berpelembagaan\n\u2022 Kedudukan istimewa orang Melayu\n\u2022 X",
   p:{A:"Peruntukan kerusi Parlimen",B:"Kewarganegaraan jus soli",C:"Penubuhan kabinet",D:"Kuasa imigresen"},
   j:"B",
   klu:"Cari cadangan yang menjadi isu paling hangat bagi kaum bukan Melayu ketika itu, iaitu berkaitan taraf kerakyatan berdasarkan tempat lahir.",
   betul:"Draf Suruhanjaya Reid mencadangkan prinsip kewarganegaraan jus soli, iaitu taraf kerakyatan berdasarkan tempat kelahiran.",
   salah:{A:"Peruntukan kerusi Parlimen ditentukan kemudian melalui persempadanan, bukan cadangan utama draf ini.",C:"Penubuhan kabinet ialah amalan sistem pemerintahan, bukan isu utama draf perlembagaan.",D:"Kuasa imigresen menjadi isu semasa pembentukan Malaysia 1963, bukan dalam draf 1956."}},

  {n:20,tk:"T4",ms:"236",aras:"R",bab:"Kemerdekaan 1957",
   s:"Maklumat berikut berkaitan jawatankuasa yang ditubuhkan menjelang pemasyhuran kemerdekaan negara pada tahun 1957. Apakah peranan jawatankuasa tersebut?",
   stim:"Jawatankuasa Fizikal",
   p:{A:"Membina istana",B:"Memberi gaji awal",C:"Menempah bendera",D:"Mengadakan kursus protokol"},
   j:"A",
   klu:"Perkataan fizikal merujuk kepada pembinaan. Apakah bangunan yang perlu disiapkan untuk Yang di-Pertuan Agong yang pertama?",
   betul:"Jawatankuasa Fizikal bertanggungjawab menyediakan keperluan pembinaan seperti istana bagi kediaman rasmi ketua negara menjelang kemerdekaan.",
   salah:{B:"Urusan gaji bukan tugas jawatankuasa fizikal.",C:"Penempahan bendera dikendalikan oleh jawatankuasa lain.",D:"Kursus protokol bukan urusan pembinaan fizikal."}},

  {n:21,tk:"T5",ms:"6",aras:"R",bab:"Kedaulatan negara",
   s:"Bagaimanakah kedudukan raja diperkukuh dalam kerajaan Melayu tradisional?",
   p:{A:"Kesetiaan rakyat",B:"Kekayaan negara",C:"Perkahwinan siasah",D:"Permuafakatan pembesar"},
   j:"A",
   klu:"Dalam konsep daulat dan derhaka, apakah tunggak yang menjadikan seorang raja benar-benar berkuasa?",
   betul:"Ketaatan dan kesetiaan rakyat yang mutlak kepada raja, berteraskan konsep daulat dan derhaka, menjadikan kedudukan raja kukuh dan tidak boleh dicabar.",
   salah:{B:"Kekayaan negara menyokong pentadbiran tetapi bukan asas kedudukan raja.",C:"Perkahwinan siasah mengukuhkan hubungan diplomatik antara kerajaan, bukan kedudukan raja dalam negeri sendiri.",D:"Pembesar melaksanakan titah raja; permuafakatan mereka bukan sumber kedudukan raja."}},

  {n:22,tk:"T5",ms:"13",aras:"R",bab:"Perpaduan",
   s:"Bagaimanakah rakyat Malaysia memainkan peranan dalam menyokong usaha kerajaan mengekalkan perpaduan kaum?",
   p:{A:"Mewajibkan mata pelajaran Sejarah",B:"Menghayati prinsip Rukun Negara",C:"Membentuk Majlis Muhibbah Negara",D:"Menganjurkan sambutan Hari Pahlawan"},
   j:"B",
   klu:"Soalan bertanya peranan rakyat, bukan peranan kerajaan. Pilihan mana yang boleh dilakukan oleh setiap individu setiap hari?",
   betul:"Penghayatan lima prinsip Rukun Negara oleh setiap rakyat memupuk kesetiaan, kesopanan dan hormat-menghormati sehingga perpaduan kaum terpelihara.",
   salah:{A:"Mewajibkan mata pelajaran ialah tindakan kerajaan, bukan peranan rakyat.",C:"Pembentukan majlis ialah tanggungjawab kerajaan.",D:"Penganjuran sambutan rasmi juga dilaksanakan oleh pihak berkuasa, bukan rakyat secara peribadi."}},

  {n:23,tk:"T5",ms:"28-29",aras:"R",bab:"Perlembagaan Persekutuan",
   s:"Antara berikut yang manakah berkaitan ciri moden dalam Perlembagaan Persekutuan?",
   stim:"I  Sistem Beraja\nII  Kerajaan Persekutuan\nIII  Demokrasi Berparlimen\nIV  Kedudukan orang Melayu",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   j:"C",
   klu:"Asingkan ciri warisan tradisional daripada ciri yang diterima daripada amalan pemerintahan moden.",
   betul:"Kerajaan Persekutuan dan Demokrasi Berparlimen ialah ciri moden yang diterima pakai dalam Perlembagaan Persekutuan.",
   salah:{A:"Sistem Beraja ialah ciri tradisional warisan kesultanan Melayu.",B:"Kedua-dua sistem beraja dan kedudukan orang Melayu ialah ciri tradisional.",D:"Kedudukan orang Melayu ialah unsur tradisi yang dikekalkan dalam perlembagaan."}},

  {n:24,tk:"T5",ms:"30-31",aras:"S",bab:"Pindaan Perlembagaan",
   s:"Maklumat berikut berkaitan Perlembagaan Persekutuan di negara kita. Mengapakah pindaan tersebut berlaku?",
   stim:"\u2022 Pindaan Perlembagaan 1963\n\u2022 Pindaan Perlembagaan 1965",
   p:{A:"Mematuhi arahan pemerintah",B:"Mendapat pengiktirafan pihak luar",C:"Mengukuhkan kedudukan parti politik",D:"Menyesuaikan dengan keperluan semasa"},
   j:"D",
   klu:"Apa yang berlaku pada tahun 1963 dan 1965? Kedua-duanya melibatkan perubahan besar kepada bentuk negara.",
   betul:"Pindaan dibuat bagi menyesuaikan perlembagaan dengan keperluan semasa, iaitu pembentukan Malaysia pada 1963 dan pemisahan Singapura pada 1965.",
   salah:{A:"Pindaan perlembagaan melalui proses Parlimen, bukan sekadar arahan pemerintah.",B:"Pengiktirafan luar bukan tujuan pindaan perlembagaan.",C:"Perlembagaan dipinda untuk kepentingan negara, bukan kedudukan parti politik."}},

  {n:25,tk:"T5",ms:"49",aras:"R",bab:"Yang di-Pertuan Agong",
   s:"Gambar berikut adalah Yang di-Pertuan Agong Malaysia ke-17. Apakah kuasa baginda dalam bidang perundangan?",
   stim:"[Gambar: Kebawah Duli Yang Maha Mulia Seri Paduka Baginda Yang di-Pertuan Agong Sultan Ibrahim]",
   p:{A:"Mengisytiharkan darurat",B:"Melantik ahli diplomat",C:"Mengetuai angkatan tentera",D:"Menangguhkan hukuman mahkamah"},
   j:"A",
   klu:"Bahagikan kuasa baginda kepada tiga: perundangan, eksekutif dan kehakiman. Pilihan mana melibatkan kuasa mengeluarkan ordinan?",
   betul:"Dalam bidang perundangan, Yang di-Pertuan Agong berkuasa mengisytiharkan darurat dan memerintah melalui ordinan apabila keselamatan negara terancam.",
   salah:{B:"Pelantikan diplomat ialah kuasa dalam bidang eksekutif.",C:"Ketua Angkatan Tentera ialah kuasa dalam bidang eksekutif.",D:"Pengampunan atau penangguhan hukuman ialah kuasa dalam bidang kehakiman."}},

  {n:26,tk:"T5",ms:"53",aras:"R",bab:"Parlimen",
   s:"Peranan Parlimen di negara kita ialah",
   p:{A:"menentukan bentuk hukuman",B:"mentafsir undang-undang",C:"menjalankan pentadbiran",D:"menyemak dasar kerajaan"},
   j:"D",
   klu:"Ingat pengasingan kuasa: badan perundangan, eksekutif dan kehakiman. Tugas mana milik Parlimen?",
   betul:"Parlimen berperanan menggubal undang-undang serta menyemak dan membahaskan dasar kerajaan melalui persidangan Dewan Rakyat dan Dewan Negara.",
   salah:{A:"Penentuan hukuman ialah bidang kuasa badan kehakiman.",B:"Tafsiran undang-undang dilakukan oleh mahkamah.",C:"Pentadbiran dijalankan oleh badan eksekutif iaitu jemaah menteri."}},

  {n:27,tk:"T5",ms:"71",aras:"S",bab:"Kerajaan tempatan",
   s:"Gambar berikut menunjukkan aktiviti penjaja di negara kita. Pihak manakah yang bertanggungjawab mengeluarkan lesen aktiviti tersebut?",
   stim:"[Gambar: Aktiviti penjaja di pasar. Sumber: FAMA Negeri Sembilan]",
   p:{A:"Badan Berkanun",B:"Pihak Berkuasa Tempatan",C:"Dewan Perniagaan Usahawan Kecil",D:"Kerajaan Persekutuan"},
   j:"B",
   klu:"Siapa yang menguruskan pasar, kebersihan bandar dan lesen perniagaan kecil di kawasan anda?",
   betul:"Pihak Berkuasa Tempatan seperti majlis perbandaran dan majlis daerah berkuasa mengeluarkan lesen penjaja dan mengawal selia aktiviti perniagaan kecil.",
   salah:{A:"Badan berkanun ditubuhkan untuk tugas khusus tertentu, bukan pengeluaran lesen penjaja.",C:"Dewan perniagaan ialah badan persatuan peniaga, tiada kuasa mengeluarkan lesen.",D:"Kerajaan Persekutuan menguruskan hal ehwal negara, bukan lesen penjaja di peringkat tempatan."}},

  {n:28,tk:"T5",ms:"75",aras:"S",bab:"Khazanah laut",
   s:"Bagaimanakah kerajaan Malaysia memulihara khazanah laut untuk warisan generasi akan datang?",
   stim:"I  Melaksanakan program restorasi karang\nII  Mengisytiharkan Deklarasi Kuala Lumpur\nIII  Mendapatkan pengiktirafan UNESCO\nIV  Mengawal selia kawasan perairan",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   j:"B",
   klu:"Cari dua tindakan yang benar-benar berlaku di dalam laut dan kawasan perairan negara.",
   betul:"Program restorasi terumbu karang dan kawalan selia kawasan perairan seperti taman laut merupakan langkah langsung memulihara khazanah laut negara.",
   salah:{A:"Deklarasi Kuala Lumpur berkaitan isu serantau, bukan tindakan pemuliharaan laut secara langsung.",C:"Pengiktirafan UNESCO berkaitan tapak warisan, bukan kaedah pemuliharaan laut.",D:"Kedua-dua tindakan ini tidak melibatkan pemuliharaan sumber laut secara langsung."}},

  {n:29,tk:"T5",ms:"97",aras:"R",bab:"Pembentukan Malaysia",
   s:"Mengapakah Filipina menentang penubuhan Malaysia pada tahun 1963?",
   p:{A:"Mengembangkan ideologi neokolonialisme",B:"Membentuk Kesatuan Kalimantan Utara",C:"Melindungi kepentingan ekonomi",D:"Menuntut wilayah Sabah"},
   j:"D",
   klu:"Bezakan hujah Filipina daripada hujah Indonesia. Filipina membangkitkan isu warisan Kesultanan Sulu.",
   betul:"Filipina mendakwa Sabah ialah wilayah miliknya berdasarkan tuntutan warisan Kesultanan Sulu, lalu membantah kemasukan Sabah ke dalam Malaysia.",
   salah:{A:"Tuduhan neokolonialisme ialah hujah Indonesia, bukan Filipina.",B:"Kesatuan Kalimantan Utara diperjuangkan oleh A.M. Azahari melalui pemberontakan Brunei.",C:"Kepentingan ekonomi bukan alasan rasmi bantahan Filipina."}},

  {n:30,tk:"T5",ms:"108",aras:"T",bab:"Konfrontasi",
   s:"Maklumat berikut berkaitan dengan mesyuarat Menteri Luar di Manila. Apakah persetujuan yang dicapai dalam mesyuarat tersebut?",
   stim:"7 hingga 11 Jun 1963\n\u2022 Tun Abdul Razak Hussein (Malaysia)\n\u2022 Dr. Subandrio (Indonesia)",
   p:{A:"Memantapkan perkhidmatan perisikan",B:"Mengadakan kerjasama ketenteraan",C:"Menangani ancaman pengganas",D:"Membincangkan masalah konfrontasi"},
   j:"D",
   klu:"Apakah isu terbesar antara Malaysia dan Indonesia pada tahun 1963 yang perlu diselesaikan melalui rundingan?",
   betul:"Mesyuarat Menteri Luar di Manila diadakan untuk membincangkan dan mencari jalan penyelesaian terhadap masalah konfrontasi Indonesia terhadap pembentukan Malaysia.",
   salah:{A:"Perkhidmatan perisikan bukan agenda mesyuarat tersebut.",B:"Kerjasama ketenteraan mustahil dicapai ketika hubungan sedang tegang.",C:"Ancaman pengganas bukan isu utama dalam rundingan Manila."}},

  {n:31,tk:"T5",ms:"121",aras:"T",bab:"Ancaman komunis",
   s:"Maklumat berikut berkaitan strategi untuk mengatasi ancaman komunis di Sarawak selepas pembentukan Malaysia. Apakah X?",
   stim:"X\n\u2022 Mengisytiharkan kawasan putih\n\u2022 Tawaran pengampunan",
   p:{A:"Perang Saraf",B:"Kampung Baru",C:"Operasi Sri Aman",D:"Pendaftaran Kebangsaan"},
   j:"A",
   klu:"Kedua-dua tindakan ini menyerang semangat dan keyakinan pengganas, bukan menyerang mereka dengan senjata.",
   betul:"Perang saraf ialah strategi melemahkan semangat komunis. Pengisytiharan kawasan putih dan tawaran pengampunan digunakan untuk memujuk anggota komunis menyerah diri serta memutuskan sokongan orang ramai kepada mereka.",
   salah:{B:"Rancangan Kampung Baru ialah penempatan semula penduduk semasa darurat di Tanah Melayu.",C:"Operasi Sri Aman ialah operasi rundingan penyerahan diri Bong Kee Chok pada tahun 1973, bukan strategi yang disenaraikan dalam kotak.",D:"Pendaftaran Kebangsaan ialah langkah mengenal pasti penduduk melalui kad pengenalan."}},

  {n:32,tk:"T5",ms:"128",aras:"S",bab:"Rancangan Malaysia Pertama",
   s:"Maklumat berikut berkaitan isu pembangunan ekonomi dalam Rancangan Malaysia Pertama (1966-1970). Bagaimanakah masalah tersebut diatasi?",
   stim:"\u2022 Peluang pekerjaan yang terhad\n\u2022 Kadar pengangguran meningkat",
   p:{A:"Memulih kawasan tanah terbiar",B:"Menggalakkan penubuhan koperasi",C:"Menubuhkan pusat latihan vokasional",D:"Mengawal kadar kelahiran"},
   j:"C",
   klu:"Untuk mendapat pekerjaan, apa yang paling diperlukan oleh belia ketika itu?",
   betul:"Pusat latihan vokasional dan kemahiran ditubuhkan bagi melahirkan tenaga kerja mahir supaya rakyat berpeluang mendapat pekerjaan dan mengurangkan pengangguran.",
   salah:{A:"Pemulihan tanah terbiar menyelesaikan masalah pertanian, bukan pengangguran secara langsung.",B:"Koperasi membantu ekonomi luar bandar tetapi bukan langkah utama menangani pengangguran.",D:"Kawalan kadar kelahiran bukan dasar yang dilaksanakan untuk masalah ini."}},

  {n:33,tk:"T5",ms:"148-149",aras:"S",bab:"Bahasa kebangsaan",
   s:"Bagaimanakah kerajaan memartabatkan Bahasa Melayu sebagai bahasa kebangsaan?",
   stim:"I  Menganjurkan Minggu Perpaduan\nII  Menubuhkan Universiti Kebangsaan Malaysia\nIII  Mewujudkan Institut Alam dan Tamadun Melayu\nIV  Melaksanakan program Citrawarna Malaysia",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   j:"C",
   klu:"Cari dua institusi yang benar-benar menggunakan dan mengkaji bahasa Melayu sebagai bahasa ilmu.",
   betul:"Universiti Kebangsaan Malaysia menjadikan Bahasa Melayu bahasa pengantar ilmu, manakala Institut Alam dan Tamadun Melayu (ATMA) mengkaji dan mengembangkan khazanah bahasa serta tamadun Melayu.",
   salah:{A:"Minggu Perpaduan bertujuan memupuk perpaduan kaum, bukan memartabatkan bahasa.",B:"Citrawarna Malaysia ialah program promosi pelancongan dan kebudayaan.",D:"Citrawarna Malaysia tidak berkaitan usaha memartabatkan bahasa kebangsaan."}},

  {n:34,tk:"T5",ms:"150",aras:"R",bab:"Dasar Kebudayaan Kebangsaan",
   s:"Dasar Kebudayaan Kebangsaan telah digubal pada tahun 1971. Mengapakah dasar tersebut diperkenalkan?",
   p:{A:"Memupuk semangat kenegerian",B:"Memperkukuh integrasi nasional",C:"Menghalang kemasukan pengaruh barat",D:"Mengawal penggunaan bahasa asing"},
   j:"B",
   klu:"Perhatikan tahun 1971. Apakah peristiwa besar yang berlaku dua tahun sebelumnya dan apakah yang cuba diperbaiki oleh kerajaan?",
   betul:"Dasar Kebudayaan Kebangsaan digubal selepas peristiwa 13 Mei 1969 untuk membentuk identiti nasional dan memperkukuh integrasi serta perpaduan rakyat berbilang kaum.",
   salah:{A:"Semangat kenegerian bertentangan dengan matlamat menyatukan rakyat di peringkat kebangsaan.",C:"Dasar ini tidak bersifat menutup pintu kepada budaya luar sepenuhnya.",D:"Kawalan bahasa asing bukan matlamat dasar kebudayaan."}},

  {n:35,tk:"T5",ms:"158",aras:"T",bab:"Rukun Negara",
   s:"Rajah berikut menunjukkan matlamat Rukun Negara untuk melahirkan rakyat yang bersatu padu. Apakah X?",
   stim:"Matlamat Rukun Negara:\nMasyarakat Demokratik \u2022 Masyarakat Liberal \u2022 Negara Bersatu \u2022 Masyarakat Progresif \u2022 X",
   p:{A:"Masyarakat adil",B:"Masyarakat majmuk",C:"Masyarakat berinovasi",D:"Masyarakat penyayang"},
   j:"A",
   klu:"Hafal lima matlamat Rukun Negara. Satu daripadanya berkaitan pembahagian kekayaan negara secara saksama.",
   betul:"Salah satu matlamat Rukun Negara ialah mewujudkan masyarakat yang adil, iaitu kemakmuran negara dinikmati bersama secara adil dan saksama.",
   salah:{B:"Masyarakat majmuk ialah keadaan sedia ada masyarakat Malaysia, bukan matlamat Rukun Negara.",C:"Masyarakat berinovasi ialah hasrat dasar pembangunan, bukan matlamat Rukun Negara.",D:"Masyarakat penyayang ialah gagasan Wawasan 2020, bukan matlamat Rukun Negara."}},

  {n:36,tk:"T5",ms:"169",aras:"S",bab:"Rancangan Buku Hijau",
   s:"Gambar berikut menunjukkan Rancangan Buku Hijau yang dilancarkan oleh Tun Abdul Razak bin Hussein pada 20 Disember 1974. Mengapakah rancangan tersebut diperkenalkan?",
   stim:"[Gambar: Buku Rancangan Buku Hijau, Panduan Tindakan Daerah]",
   p:{A:"Membina kemudahan asas",B:"Memantau projek pembangunan",C:"Menambah pengeluaran makanan",D:"Membangunkan bandar terancang"},
   j:"C",
   klu:"Warna hijau merujuk kepada tanaman. Rakyat digalakkan bercucuk tanam dan menternak di kawasan sekitar rumah.",
   betul:"Rancangan Buku Hijau menggalakkan rakyat bercucuk tanam dan menternak bagi menambah pengeluaran makanan negara serta mengurangkan import bahan makanan.",
   salah:{A:"Pembinaan kemudahan asas ialah tujuan rancangan pembangunan luar bandar yang lain.",B:"Pemantauan projek dilakukan melalui Bilik Gerakan Negara.",D:"Pembangunan bandar terancang tiada kaitan dengan Rancangan Buku Hijau."}},

  {n:37,tk:"T5",ms:"176",aras:"T",bab:"Dasar Pembangunan Nasional",
   s:"Institusi berikut ditubuhkan untuk mencapai matlamat Dasar Pembangunan Nasional (DPN). Apakah kesan penubuhan institusi tersebut?",
   stim:"\u2022 Pusat Latihan Kemahiran Giatmara\n\u2022 Institut Latihan Perindustrian (ILP)",
   p:{A:"Pelaburan luar berkembang",B:"Pendapatan rakyat bertambah",C:"Perkhidmatan kerajaan diperkasa",D:"Program pertukaran pelajar dipergiat"},
   j:"B",
   klu:"Apa yang berlaku kepada seseorang selepas memperoleh kemahiran dan mendapat pekerjaan yang lebih baik?",
   betul:"Latihan kemahiran melahirkan tenaga kerja mahir yang berpeluang mendapat pekerjaan bergaji lebih baik, lalu meningkatkan pendapatan rakyat dan membasmi kemiskinan.",
   salah:{A:"Pelaburan luar dipengaruhi dasar ekonomi dan insentif, bukan kesan langsung institusi latihan.",C:"Institusi ini melatih tenaga kerja industri, bukan memperkasa perkhidmatan awam.",D:"Pertukaran pelajar bukan matlamat penubuhan Giatmara dan ILP."}},

  {n:38,tk:"T5",ms:"208",aras:"R",bab:"Dasar luar",
   s:"Bagaimanakah Malaysia mengatasi cabaran politik antarabangsa pada tahun 1970-an?",
   p:{A:"Melaksanakan dasar berkecuali",B:"Mengukuhkan hubungan dengan barat",C:"Meneruskan dasar anti komunis",D:"Menyertai blok sterling"},
   j:"A",
   klu:"Pada era Tun Abdul Razak, dasar luar berubah daripada pro-Barat kepada satu pendirian baharu yang menjadi asas kepada ZOPFAN.",
   betul:"Malaysia melaksanakan dasar berkecuali dan tidak berpihak kepada mana-mana blok kuasa besar, sekali gus melahirkan gagasan ZOPFAN pada tahun 1971.",
   salah:{B:"Hubungan pro-Barat ialah ciri dasar luar tahap pertama pada era Tunku Abdul Rahman.",C:"Malaysia mula menjalin hubungan dengan negara komunis seperti China pada 1974.",D:"Blok sterling ialah pengaturan kewangan, bukan penyelesaian cabaran politik antarabangsa."}},

  {n:39,tk:"T5",ms:"232",aras:"R",bab:"Kemelesetan ekonomi 1997",
   s:"Malaysia menghadapi kemelesetan ekonomi pada tahun 1997-1998. Bagaimanakah kerajaan mengatasi masalah tersebut?",
   p:{A:"Membuat pinjaman dengan negara lain",B:"Membawa masuk pekerja asing",C:"Menambat mata wang negara",D:"Memperkenalkan saham bumiputera"},
   j:"C",
   klu:"Malaysia menolak bantuan IMF. Apakah langkah berani yang diambil terhadap nilai ringgit pada 1 September 1998?",
   betul:"Kerajaan menambat nilai ringgit pada kadar RM3.80 kepada satu dolar Amerika Syarikat dan mengenakan kawalan modal bagi menstabilkan ekonomi negara.",
   salah:{A:"Malaysia menolak pinjaman dan syarat IMF, sebaliknya menyelesaikan krisis dengan kaedah sendiri.",B:"Kemasukan pekerja asing bukan langkah mengatasi kemelesetan.",D:"Saham bumiputera diperkenalkan sebagai dasar pemilikan ekuiti, bukan penyelesaian krisis mata wang."}},

  {n:40,tk:"T5",ms:"234",aras:"S",bab:"Isu antarabangsa",
   s:"Mengapakah isu keganasan Israel terhadap Palestin menjadi perhatian Malaysia?",
   stim:"I  Menangani masalah kemiskinan\nII  Mewujudkan kerjasama ekonomi\nIII  Menghormati kedaulatan negara lain\nIV  Menegakkan prinsip keadilan",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   j:"D",
   klu:"Malaysia bersuara di PBB atas dasar prinsip, bukan atas kepentingan ekonomi.",
   betul:"Malaysia memperjuangkan isu Palestin kerana berpegang pada prinsip keadilan sejagat dan penghormatan terhadap kedaulatan sesebuah negara yang merdeka.",
   salah:{A:"Kemiskinan dan kerjasama ekonomi bukan asas pendirian Malaysia dalam isu ini.",B:"Masalah kemiskinan bukan sebab utama Malaysia membangkitkan isu Palestin.",C:"Kerjasama ekonomi tidak berkaitan dengan pendirian prinsip Malaysia."}}
  ]
}
};

BANK.pahang = {
  nama:"Percubaan SPM Pahang 2026",
  kod:"1249/1 &middot; Peperiksaan Percubaan Tingkatan 5 2026",
  perincian:"40 soalan objektif. Cadangan jawapan rasmi berserta rujukan muka surat buku teks Tingkatan 4 dan Tingkatan 5.",
  soalan:[
  {n:1,tk:"T4",ms:"4",bab:"Kerajaan Alam Melayu",
   s:"Kerajaan Alam Melayu yang mengamalkan undang-undang Kutara Manawa ialah",
   p:{A:"Angkor",B:"Funan",C:"Majapahit",D:"Srivijaya"},
   j:"C",
   klu:"Undang-undang ini berasaskan kitab Hindu dan digunakan oleh sebuah kerajaan besar di Pulau Jawa.",
   betul:"Kutara Manawa ialah undang-undang bertulis yang diamalkan oleh kerajaan Majapahit dan menjadi panduan pentadbiran serta kehakiman kerajaan tersebut.",
   salah:{A:"Angkor terkenal dengan seni bina candi dan sistem pengairan, bukan Kutara Manawa.",B:"Funan ialah kerajaan agraria terawal di Asia Tenggara dan tidak dikaitkan dengan undang-undang ini.",D:"Srivijaya sebuah kerajaan maritim yang lebih dikenali melalui kuasa laut dan perdagangannya."}},

  {n:2,tk:"T4",ms:"9",bab:"Kesultanan Melayu Melaka",
   s:"Apakah tugas Bendahara dalam Kesultanan Melayu Melaka?",
   p:{A:"Mengetuai pentadbiran",B:"Mengurus pelabuhan",C:"Menjaga perairan",D:"Melindungi kota"},
   j:"A",
   klu:"Bendahara ialah pembesar berpangkat tertinggi selepas sultan. Siapakah yang menjadi penasihat utama sultan?",
   betul:"Bendahara ialah pembesar tertinggi yang mengetuai pentadbiran negeri, menjadi penasihat utama sultan dan ketua kepada semua pembesar.",
   salah:{B:"Pengurusan pelabuhan ialah tugas Syahbandar.",C:"Keselamatan perairan dijaga oleh Laksamana.",D:"Pertahanan kota dan keamanan dalam negeri dijaga oleh Temenggung."}},

  {n:3,tk:"T4",ms:"23",bab:"Tafsiran nasionalisme",
   s:"Maklumat berikut berkaitan tafsiran nasionalisme menurut pandangan Dr Burhanuddin al-Helmi. Apakah kesan tafsiran tersebut kepada generasi masa kini?",
   stim:"Perjuangan menentang penjajah hendaklah ada persatuan dan perpaduan yang kukuh.",
   p:{A:"Membentuk masyarakat baharu",B:"Melahirkan perasaan kekitaan",C:"Memupuk sikap individualistik",D:"Mewujudkan semangat perkauman"},
   j:"B",
   klu:"Perkataan kunci ialah persatuan dan perpaduan. Apakah perasaan yang lahir apabila rakyat merasakan mereka satu keluarga besar?",
   betul:"Penekanan terhadap persatuan dan perpaduan melahirkan perasaan kekitaan, iaitu semangat sepunya dan rasa saling memiliki dalam kalangan rakyat berbilang kaum.",
   salah:{A:"Pembentukan masyarakat baharu bukan kesan langsung tafsiran perpaduan tersebut.",C:"Sikap individualistik bertentangan sama sekali dengan semangat perpaduan.",D:"Semangat perkauman memecahbelahkan rakyat, bukan menyatukan seperti yang diperjuangkan."}},

  {n:4,tk:"T4",ms:"43",bab:"Tokoh nasionalisme",
   s:"Apakah sumbangan Ibu Zain kepada negara?",
   p:{A:"Menekankan pendidikan kemahiran",B:"Mementingkan perpaduan bangsa",C:"Mengamalkan budaya tempatan",D:"Mengangkat martabat wanita"},
   j:"D",
   klu:"Ibu Zain seorang guru dan penulis yang lantang memperjuangkan hak serta pendidikan golongan yang lama terpinggir.",
   betul:"Ibu Zain berjuang mengangkat martabat kaum wanita melalui pendidikan, penulisan dan penubuhan persatuan wanita supaya wanita Melayu setaraf dengan kaum lelaki.",
   salah:{A:"Pendidikan kemahiran bukan tumpuan khusus perjuangan beliau.",B:"Perpaduan bangsa diperjuangkan oleh ramai tokoh lain; sumbangan Ibu Zain lebih khusus kepada wanita.",C:"Pengamalan budaya tempatan bukan sumbangan utama yang dikaitkan dengan beliau."}},

  {n:5,tk:"T4",ms:"62",bab:"Perang Dunia Kedua",
   s:"Apakah faktor yang menamatkan Perang Dunia Kedua di Eropah?",
   stim:"I  Kerjasama strategi serangan\nII  Kerjasama kuasa besar\nIII  Perjanjian gencatan senjata\nIV  Persetujuan rundingan damai",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   j:"A",
   klu:"Perang di Eropah tamat apabila Jerman menyerah kalah, bukan melalui meja rundingan. Apakah yang dilakukan Britain, Amerika Syarikat dan Soviet Union?",
   betul:"Kuasa Berikat bekerjasama merancang strategi serangan bersama seperti pendaratan Normandy sehingga Jerman tewas dan menyerah kalah tanpa syarat.",
   salah:{B:"Tiada rundingan damai antara Berikat dengan Jerman; Jerman menyerah kalah tanpa syarat.",C:"Gencatan senjata bukan cara perang di Eropah ditamatkan.",D:"Kedua-dua gencatan senjata dan rundingan damai tidak berlaku sebelum kekalahan Jerman."}},

  {n:6,tk:"T4",ms:"76",bab:"Pendudukan Jepun",
   s:"Apakah tujuan penubuhan Force 136 pada tahun 1943?",
   p:{A:"Membanteras kegiatan pengganas",B:"Membendung keganasan MPAJA",C:"Menentang pendudukan Jepun",D:"Menghalang pemberontakan rakyat"},
   j:"C",
   klu:"Force 136 ditubuhkan semasa Tanah Melayu berada di bawah kuasa siapa? Siapa musuh mereka ketika itu?",
   betul:"Force 136 ditubuhkan oleh British bersama penduduk tempatan untuk menjalankan kerja risikan dan gerakan bawah tanah menentang pendudukan tentera Jepun.",
   salah:{A:"Pembanterasan pengganas komunis berlaku semasa darurat selepas perang tamat.",B:"Force 136 malah bekerjasama dengan MPAJA menentang Jepun.",D:"Force 136 bukan pasukan untuk menghalang rakyat tempatan."}},

  {n:7,tk:"T4",ms:"102",bab:"Malayan Union",
   s:"Antara berikut manakah akhbar yang membantah pelaksanaan Malayan Union?",
   stim:"I  Warta Negara\nII  Suara Rakyat\nIII  Jawi Peranakan\nIV  Utusan Melayu",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   j:"B",
   klu:"Cari akhbar Melayu yang bergiat aktif sekitar tahun 1946. Ingat bahawa Jawi Peranakan terbit jauh lebih awal, pada abad ke-19.",
   betul:"Akhbar Warta Negara dan Utusan Melayu menyiarkan rencana serta tulisan yang mengecam Malayan Union dan menyeru orang Melayu bersatu menentangnya.",
   salah:{A:"Suara Rakyat bukan akhbar yang menggerakkan bantahan Malayan Union.",C:"Jawi Peranakan ialah akhbar Melayu pertama yang terbit pada tahun 1876, jauh sebelum Malayan Union.",D:"Kedua-dua akhbar ini tidak terlibat dalam bantahan Malayan Union."}},

  {n:8,tk:"T4",ms:"114-115",bab:"Penyerahan Sabah",
   s:"Mengapakah Syarikat Borneo Utara British menyerahkan Sabah kepada British pada 26 Jun 1946?",
   p:{A:"Krisis politik",B:"Pewarisan takhta",C:"Perubahan dasar",D:"Masalah kewangan"},
   j:"D",
   klu:"Selepas perang, bandar-bandar utama Sabah musnah. Apakah masalah terbesar yang dihadapi sebuah syarikat perniagaan untuk membina semula?",
   betul:"Syarikat Borneo Utara British menghadapi masalah kewangan yang serius kerana tidak mampu menanggung kos pembinaan semula Sabah yang musnah akibat Perang Dunia Kedua.",
   salah:{A:"Tiada krisis politik dalaman yang memaksa penyerahan tersebut.",B:"Sabah ditadbir oleh syarikat berpiagam, bukan melalui sistem pewarisan takhta.",C:"Perubahan dasar berlaku selepas penyerahan, bukan puncanya."}},

  {n:9,tk:"T4",ms:"132",bab:"Cadangan Raja-Raja Melayu",
   s:"Maklumat berikut berkaitan cadangan Raja-Raja Melayu dan wakil UMNO kepada wakil British dalam tahun 1946. Apakah kesan cadangan tersebut kepada pemerintahan beraja di negara kita?",
   stim:"Raja berkuasa dalam perundangan",
   p:{A:"Mengukuhkan pertahanan",B:"Menggubal perlembagaan",C:"Mengembalikan kedaulatan",D:"Menerajui kerajaan"},
   j:"C",
   klu:"Ingat apa yang hilang daripada raja-raja Melayu di bawah Malayan Union. Apakah yang dituntut semula melalui cadangan ini?",
   betul:"Cadangan mengembalikan kuasa raja dalam bidang perundangan bermakna kedaulatan raja-raja Melayu yang terhakis di bawah Malayan Union dipulihkan semula.",
   salah:{A:"Hal ehwal pertahanan kekal di bawah kuasa British.",B:"Penggubalan perlembagaan ialah proses, bukan kesan kepada institusi beraja.",D:"Pentadbiran harian diterajui oleh Pesuruhjaya Tinggi dan kemudiannya kerajaan pilihan raya, bukan raja."}},

  {n:10,tk:"T4",ms:"134",bab:"Persekutuan Tanah Melayu 1948",
   s:"Mengapakah British mengasingkan Singapura dalam Persekutuan Tanah Melayu 1948?",
   p:{A:"Kekal sebagai tanah jajahan",B:"Kekayaan bahan mentah",C:"Desakan golongan imigran",D:"Penentangan penduduk tempatan"},
   j:"A",
   klu:"Singapura pelabuhan bebas dan pangkalan tentera laut yang penting kepada British. Apakah taraf yang ingin dikekalkan British ke atasnya?",
   betul:"British mengekalkan Singapura sebagai tanah jajahan yang berasingan bagi melindungi kepentingan ekonomi pelabuhan bebas dan pangkalan tentera laut mereka di sana.",
   salah:{B:"Singapura tidak kaya dengan bahan mentah; kekuatannya ialah pelabuhan.",C:"Golongan imigran tidak mendesak pengasingan Singapura.",D:"Penduduk tempatan Tanah Melayu membantah Malayan Union, bukan menuntut pengasingan Singapura."}},

  {n:11,tk:"T4",ms:"150-151",bab:"Ancaman komunis",
   s:"Maklumat berikut berkaitan ancaman komunis terhadap penduduk tempatan. Mengapakah komunis bertindak sedemikian?",
   stim:"22 Februari 1950  \u2014  Menyerang Balai Polis Bukit Kepong\n28 Mei 1954  \u2014  Membunuh Ketua Polis Kedah",
   p:{A:"Menuntut persamaan hak",B:"Mencetuskan huru hara",C:"Membebaskan tawanan",D:"Merampas semula kuasa"},
   j:"B",
   klu:"Sasaran mereka ialah balai polis dan pegawai keselamatan. Apakah keadaan yang ingin diwujudkan supaya rakyat hilang keyakinan kepada kerajaan?",
   betul:"Serangan terhadap balai polis dan pembunuhan pegawai keselamatan bertujuan mencetuskan huru-hara serta menggugat keselamatan negara supaya rakyat hilang keyakinan terhadap kerajaan.",
   salah:{A:"Komunis tidak berjuang menuntut persamaan hak melalui keganasan bersenjata.",C:"Serangan tersebut bukan operasi membebaskan tawanan.",D:"Komunis tidak pernah memegang kuasa pemerintahan untuk dirampas semula."}},

  {n:12,tk:"T4",ms:"154",bab:"Pasukan keselamatan",
   s:"Berikut adalah pasukan keselamatan yang ditubuhkan oleh British bagi membanteras ancaman komunis. Apakah X?",
   stim:"X\n\u2022 Dikenali sebagai \u201cThe Silent Killer\u201d\n\u2022 Mengesan tempat persembunyian komunis",
   p:{A:"Polis Hutan",B:"Senoi Praaq",C:"Home Guard",D:"Special Constables"},
   j:"B",
   klu:"Pasukan ini dianggotai oleh Orang Asli yang amat mahir menjejak dalam hutan tebal.",
   betul:"Senoi Praaq yang dianggotai Orang Asli terkenal dengan gelaran The Silent Killer kerana kepakaran mereka menjejak dan mengesan tempat persembunyian komunis di dalam hutan.",
   salah:{A:"Polis Hutan menjalankan rondaan dan serangan di kawasan pedalaman tetapi bukan yang bergelar The Silent Killer.",C:"Home Guard menjaga keselamatan kampung dan kampung baru.",D:"Special Constables mengawal keselamatan estet dan lombong."}},

  {n:13,tk:"T4",ms:"179",bab:"Sistem Ahli",
   s:"Penduduk tempatan dilantik sebagai Ahli dalam Sistem Ahli pada tahun 1951. Mengapakah pelantikan tersebut penting kepada negara?",
   p:{A:"Mengekalkan sistem pentadbiran tradisional",B:"Mengukuhkan kuasa politik bumiputera",C:"Persediaan ke arah berkerajaan sendiri",D:"Penjimatan perbelanjaan kerajaan"},
   j:"C",
   klu:"Sistem Ahli sering disebut sebagai cikal bakal sistem kabinet. Apakah tujuan sebenar British melatih penduduk tempatan memegang portfolio?",
   betul:"Sistem Ahli memberi latihan dan pendedahan kepada penduduk tempatan mentadbir negara, menjadikannya persediaan awal ke arah berkerajaan sendiri dan asas kepada sistem kabinet hari ini.",
   salah:{A:"Sistem Ahli memperkenalkan amalan pentadbiran moden, bukan mengekalkan sistem tradisional.",B:"Ahli dilantik daripada pelbagai kaum, bukan untuk mengukuhkan kuasa satu kaum sahaja.",D:"Penjimatan perbelanjaan bukan tujuan penubuhan Sistem Ahli."}},

  {n:14,tk:"T4",ms:"184",bab:"UMNO",
   s:"Apakah perjuangan United Malays National Organization (UMNO) pada tahun 1946?",
   p:{A:"Menghalang kemasukan imigran",B:"Mewujudkan pentadbiran Islam",C:"Menekankan perpaduan kaum",D:"Menentang Malayan Union"},
   j:"D",
   klu:"Perhatikan tahun 1946. Apakah gagasan British yang menghapuskan kuasa raja dan memberi kerakyatan sama rata ketika itu?",
   betul:"UMNO ditubuhkan pada 11 Mei 1946 dengan matlamat utama menentang gagasan Malayan Union yang menghapuskan kedaulatan raja-raja Melayu dan hak istimewa orang Melayu.",
   salah:{A:"Isu imigran bukan matlamat penubuhan UMNO pada tahun tersebut.",B:"UMNO ialah parti kebangsaan, bukan gerakan menubuhkan pentadbiran Islam.",C:"Kerjasama antara kaum berkembang kemudian menerusi Parti Perikatan pada tahun 1950-an."}},

  {n:15,tk:"T4",ms:"197",bab:"Pilihan raya",
   s:"Maklumat berikut berkaitan perkembangan pilihan raya di Persekutuan Tanah Melayu. Mengapakah parti tersebut memperoleh kemenangan?",
   stim:"1954 \u2014 Pilihan Raya Peringkat Negeri\nParti Perikatan menang 226 daripada 268 kerusi",
   p:{A:"Kerjasama antara kaum",B:"Peranan Raja-raja Melayu",C:"Sokongan daripada British",D:"Kewibawaan calon politik"},
   j:"A",
   klu:"Perikatan ialah gabungan tiga parti yang mewakili tiga kaum utama. Apakah rahsia kekuatannya berbanding parti lain?",
   betul:"Kemenangan besar Perikatan berpunca daripada kerjasama antara kaum menerusi gabungan UMNO, MCA dan MIC yang berjaya meraih sokongan pengundi semua kaum.",
   salah:{B:"Raja-raja Melayu tidak terlibat dalam pertandingan pilihan raya.",C:"British bersikap neutral dan tidak menyokong mana-mana parti.",D:"Kewibawaan calon menyumbang, tetapi kekuatan utama ialah formula kerjasama kaum."}},

  {n:16,tk:"T4",ms:"204-206",bab:"Majlis Perundangan Persekutuan 1955",
   s:"Penubuhan Majlis Perundangan Persekutuan 1955 telah membawa perubahan yang besar kepada negara. Apakah perubahan tersebut?",
   stim:"I  Pengukuhan pemerintahan beraja\nII  Perkembangan amalan demokrasi\nIII  Pembentukan kabinet pertama\nIV  Pelantikan jawatan ketua negara",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   j:"C",
   klu:"Buat kali pertama rakyat memilih wakil melalui undi, dan Tunku Abdul Rahman dilantik sebagai Ketua Menteri lalu membentuk barisan menterinya.",
   betul:"Pilihan raya 1955 memperkembang amalan demokrasi kerana rakyat memilih wakil sendiri, dan kemenangan Perikatan membawa kepada pembentukan kabinet yang pertama di bawah Tunku Abdul Rahman.",
   salah:{A:"Pemerintahan beraja tidak berubah kesan penubuhan majlis tersebut.",B:"Jawatan ketua negara iaitu Yang di-Pertuan Agong hanya wujud selepas merdeka pada tahun 1957.",D:"Pelantikan ketua negara bukan kesan penubuhan Majlis Perundangan Persekutuan 1955."}},

  {n:17,tk:"T4",ms:"216-217",bab:"Rombongan Merdeka",
   s:"Gambar berikut berkaitan peristiwa bersejarah di negara kita. Rombongan tersebut diketuai oleh",
   stim:"[Gambar: Rombongan Merdeka ke London, Januari 1956]",
   p:{A:"Dato Onn Jaafar",B:"Dato Abdul Razak Hussein",C:"Dr Ismail Abdul Rahman",D:"Tunku Abdul Rahman"},
   j:"D",
   klu:"Ketua rombongan itu ialah Ketua Menteri Persekutuan Tanah Melayu ketika itu, yang kemudiannya memasyhurkan kemerdekaan.",
   betul:"Rombongan Merdeka ke London pada Januari 1956 diketuai oleh Tunku Abdul Rahman selaku Ketua Menteri, bersama wakil UMNO, MCA, MIC dan Raja-Raja Melayu.",
   salah:{A:"Dato Onn Jaafar telah meninggalkan UMNO sebelum rundingan kemerdekaan berlangsung.",B:"Dato Abdul Razak Hussein ialah ahli rombongan, bukan ketuanya.",C:"Dr Ismail Abdul Rahman turut menganggotai rombongan tetapi bukan sebagai ketua."}},

  {n:18,tk:"T4",ms:"225",bab:"Perlembagaan 1957",
   s:"Mengapakah rakyat keturunan Melayu diberi kedudukan istimewa dalam Perlembagaan Persekutuan Tanah Melayu 1957?",
   p:{A:"Merupakan penduduk asal",B:"Menjadi golongan majoriti",C:"Memiliki kelakuan yang baik",D:"Mengamalkan budaya tempatan"},
   j:"A",
   klu:"Fikirkan siapakah pemilik asal negeri-negeri Melayu sebelum kedatangan kuasa luar dan kemasukan imigran.",
   betul:"Orang Melayu diberi kedudukan istimewa kerana merupakan penduduk asal atau bumiputera negeri ini yang mewarisi negara dan sistem beraja sejak sebelum kedatangan penjajah.",
   salah:{B:"Kedudukan istimewa bukan berasaskan bilangan penduduk, malah orang Melayu bukan majoriti mutlak ketika itu.",C:"Perlembagaan tidak berasaskan penilaian kelakuan sesuatu kaum.",D:"Amalan budaya bukan asas peruntukan perlembagaan tersebut."}},

  {n:19,tk:"T4",ms:"236",bab:"Kemerdekaan 1957",
   s:"Jawatankuasa Sambutan ditubuhkan untuk memeriahkan kemerdekaan negara. Apakah persediaan jawatankuasa tersebut?",
   p:{A:"Membina kediaman rasmi ketua negara",B:"Menyediakan pakaian khas Menteri",C:"Memperkenalkan lagu kebangsaan",D:"Mereka cipta bendera persekutuan"},
   j:"B",
   klu:"Asingkan tugas Jawatankuasa Sambutan daripada tugas Jawatankuasa Fizikal. Sambutan berkaitan majlis dan istiadat.",
   betul:"Jawatankuasa Sambutan menguruskan persiapan istiadat kemerdekaan termasuk menyediakan pakaian khas atau pakaian istiadat bagi menteri dan tetamu kehormat.",
   salah:{A:"Pembinaan kediaman rasmi ketua negara ialah tugas Jawatankuasa Fizikal.",C:"Lagu Negaraku diperkenalkan melalui proses pemilihan sebelum itu, bukan tugas jawatankuasa sambutan.",D:"Reka bentuk bendera persekutuan telah dipilih melalui pertandingan sebelum kemerdekaan."}},

  {n:20,tk:"T4",ms:"243",bab:"AMDA",
   s:"Maklumat berikut berkaitan perjanjian antara negara kita dengan Britain. Mengapakah perjanjian tersebut ditandatangani?",
   stim:"Anglo Malayan Defence Agreement (AMDA)",
   p:{A:"Melindungi hak asasi manusia",B:"Menambahkan aset ketenteraan",C:"Menjamin kebebasan mentadbir",D:"Menguatkan sistem pertahanan"},
   j:"D",
   klu:"Perkataan defence dalam nama perjanjian sudah memberi petunjuk. Negara yang baru merdeka masih menghadapi ancaman komunis.",
   betul:"AMDA ditandatangani bagi menguatkan sistem pertahanan negara yang baharu merdeka kerana Persekutuan Tanah Melayu masih menghadapi ancaman komunis dan belum mempunyai angkatan tentera yang kukuh.",
   salah:{A:"Perjanjian ini berkaitan pertahanan, bukan hak asasi manusia.",B:"Penambahan aset ialah kesan sampingan, bukan tujuan utama perjanjian.",C:"Kebebasan mentadbir telah pun diperoleh melalui kemerdekaan pada tahun 1957."}},

  {n:21,tk:"T5",ms:"5",bab:"Kedaulatan negara",
   s:"Maklumat berikut berkaitan dengan konsep kedaulatan. Apakah kebebasan yang dimaksudkan oleh tokoh tersebut?",
   stim:"Tun Dr Mohamed Salleh Abas menyatakan asas bagi sebuah negara yang merdeka ialah memiliki kebebasan tanpa telunjuk asing.",
   p:{A:"Mencapai kecemerlangan hubungan luar",B:"Menjadi kuasa politik unggul dunia",C:"Mempunyai hak mengurus negeri",D:"Meluaskan pengaruh ketenteraan"},
   j:"C",
   klu:"Tanpa telunjuk asing bermaksud tiada kuasa luar yang boleh memerintah kita. Apakah hak asas sebuah negara berdaulat?",
   betul:"Kebebasan yang dimaksudkan ialah hak mutlak sesebuah negara mengurus dan mentadbir hal ehwal negerinya sendiri tanpa campur tangan atau arahan kuasa asing.",
   salah:{A:"Hubungan luar yang cemerlang ialah hasil dasar luar, bukan takrifan kedaulatan.",B:"Menjadi kuasa unggul dunia bukan syarat sebuah negara berdaulat.",D:"Perluasan pengaruh ketenteraan bertentangan dengan prinsip kedaulatan negara lain."}},

  {n:22,tk:"T5",ms:"10-11",bab:"Kepentingan kedaulatan",
   s:"Maklumat berikut berkaitan kepentingan mewujudkan negara yang berdaulat. Apakah X?",
   stim:"\u2022 Keberkesanan pentadbiran\n\u2022 Kemakmuran ekonomi\n\u2022 Kecemerlangan hubungan luar\n\u2022 X",
   p:{A:"Kesejahteraan sosial",B:"Kebebasan bersuara",C:"Kekuatan ketenteraan",D:"Kewibawaan pemimpin"},
   j:"A",
   klu:"Tiga yang tersenarai merangkumi aspek politik, ekonomi dan hubungan antarabangsa. Aspek besar manakah yang masih tertinggal?",
   betul:"Kesejahteraan sosial melengkapkan kepentingan kedaulatan kerana negara berdaulat mampu menjamin keamanan, perpaduan dan kualiti hidup rakyatnya.",
   salah:{B:"Kebebasan bersuara ialah satu hak dalam perlembagaan, bukan aspek besar kepentingan kedaulatan.",C:"Kekuatan ketenteraan ialah alat mempertahankan kedaulatan, bukan kepentingan yang disenaraikan.",D:"Kewibawaan pemimpin ialah faktor, bukan kepentingan kedaulatan kepada negara."}},

  {n:23,tk:"T5",ms:"25-27",bab:"Sejarah perlembagaan",
   s:"Maklumat berikut berkaitan sejarah pembentukan undang-undang di Malaysia. Apakah kesan perkembangan tersebut kepada negara?",
   stim:"1877  \u2014  Mesyuarat Majlis\n1946  \u2014  Majlis Undangan Negeri\n1948  \u2014  Persekutuan Tanah Melayu",
   p:{A:"Pemberian kuasa autonomi",B:"Penggubalan perlembagaan",C:"Pengukuhan kuasa raja",D:"Penetapan sempadan"},
   j:"B",
   klu:"Ketiga-tiga peristiwa ini merupakan tahap perkembangan sehingga negara memiliki undang-undang tertinggi sendiri.",
   betul:"Perkembangan berperingkat institusi perundangan tersebut menjadi asas kepada penggubalan Perlembagaan Persekutuan sebagai undang-undang tertinggi negara.",
   salah:{A:"Kuasa autonomi tidak diberikan menerusi ketiga-tiga peristiwa tersebut.",C:"Kuasa raja sebenarnya semakin terbatas menerusi perkembangan perlembagaan ini.",D:"Penetapan sempadan bukan kesan perkembangan sistem perundangan."}},

  {n:24,tk:"T5",ms:"30-31",bab:"Pindaan Perlembagaan 1963",
   s:"Apakah perkara yang termaktub dalam pindaan Perlembagaan 1963?",
   stim:"I  Mewujudkan Majlis Sultan-Sultan\nII  Membentuk Majlis Undangan Negeri\nIII  Menubuhkan Mahkamah Tinggi Borneo\nIV  Memperkenalkan jawatan Yang di-Pertua Negeri",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   j:"D",
   klu:"Pindaan 1963 berlaku kerana kemasukan Sabah, Sarawak dan Singapura. Cari perkara baharu yang khusus untuk wilayah Borneo yang tiada sultan.",
   betul:"Pindaan Perlembagaan 1963 menubuhkan Mahkamah Tinggi Borneo dan memperkenalkan jawatan Yang di-Pertua Negeri bagi negeri yang tidak beraja seperti Sabah dan Sarawak.",
   salah:{A:"Majlis Raja-Raja telah wujud sejak sebelum tahun 1963.",B:"Majlis Undangan Negeri telah lama wujud di negeri-negeri Tanah Melayu.",C:"Kedua-dua perkara ini bukan perkara baharu dalam pindaan tersebut."}},

  {n:25,tk:"T5",ms:"45",bab:"Majlis Raja-Raja",
   s:"Majlis Raja-Raja bertindak sebagai pengimbang dalam sistem demokrasi di negara kita. Bagaimanakah majlis tersebut memainkan peranannya?",
   p:{A:"Memilih ahli kabinet dalam pentadbiran",B:"Menentukan bentuk hubungan diplomatik",C:"Memberi nasihat bagi pelantikan jawatan penting",D:"Menetapkan agihan peruntukan pembangunan"},
   j:"C",
   klu:"Majlis ini perlu ditanya sebelum pelantikan hakim, Ketua Audit Negara dan ahli Suruhanjaya Perkhidmatan Awam.",
   betul:"Majlis Raja-Raja berperanan memberi nasihat dan perkenan dalam pelantikan jawatan penting negara seperti hakim, Ketua Audit Negara dan ahli suruhanjaya, lalu menjadi pengimbang kepada kuasa eksekutif.",
   salah:{A:"Ahli kabinet dilantik oleh Yang di-Pertuan Agong atas nasihat Perdana Menteri.",B:"Hubungan diplomatik ditentukan oleh kerajaan melalui Kementerian Luar Negeri.",D:"Agihan peruntukan pembangunan ditetapkan melalui belanjawan yang diluluskan Parlimen."}},

  {n:26,tk:"T5",ms:"55",bab:"Pengasingan kuasa",
   s:"Mengapakah pengasingan kuasa dilaksanakan dalam sistem pemerintahan di Malaysia?",
   p:{A:"Meredakan pertikaian parti politik",B:"Memudahkan dasar kerajaan diluluskan",C:"Menyelaraskan peruntukan negeri",D:"Mewujudkan pemerintahan yang adil"},
   j:"D",
   klu:"Apa yang berlaku jika satu badan sahaja menggubal, melaksana dan menghakimi undang-undang?",
   betul:"Pengasingan kuasa antara badan perundangan, eksekutif dan kehakiman mengelakkan penyalahgunaan kuasa serta menjamin pemerintahan yang adil dan telus.",
   salah:{A:"Pengasingan kuasa bukan mekanisme menyelesaikan pertikaian parti politik.",B:"Pengasingan kuasa sebenarnya menapis dan mengimbangi, bukan memudahkan kelulusan dasar.",C:"Penyelarasan peruntukan negeri dilakukan melalui Majlis Kewangan Negara."}},

  {n:27,tk:"T5",ms:"69",bab:"Senarai Persekutuan",
   s:"Antara berikut manakah berkaitan bidang kuasa Senarai Persekutuan?",
   stim:"I  Mengawal hal ehwal luar negeri\nII  Menguruskan sistem pertahanan\nIII  Menyediakan kemudahan awam\nIV  Membangunkan kemajuan tanah",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   j:"A",
   klu:"Tanah dan kemudahan tempatan sentiasa milik siapa? Ingat kes tanah dan air yang selalu diuruskan kerajaan negeri.",
   betul:"Hal ehwal luar negeri dan pertahanan terletak di bawah Senarai Persekutuan kerana melibatkan kedaulatan dan keselamatan seluruh negara.",
   salah:{B:"Kemajuan tanah terletak di bawah Senarai Negeri.",C:"Kemudahan awam tempatan diuruskan oleh kerajaan negeri dan pihak berkuasa tempatan.",D:"Kedua-dua perkara ini termasuk dalam bidang kuasa kerajaan negeri."}},

  {n:28,tk:"T5",ms:"80",bab:"Sistem persekutuan",
   s:"Apakah faktor yang mengukuhkan sistem persekutuan?",
   p:{A:"Pemantapan bidang kuasa Yang di-Pertuan Agong",B:"Pembentukan agensi kerajaan sebagai badan pelaksana",C:"Penyelarasan Kerajaan Persekutuan dengan Kerajaan Negeri",D:"Pemusatan kuasa kehakiman dalam perundangan"},
   j:"C",
   klu:"Sistem persekutuan bermaksud dua peringkat kerajaan berkongsi kuasa. Apakah yang mesti berlaku antara kedua-duanya?",
   betul:"Penyelarasan dan kerjasama berterusan antara Kerajaan Persekutuan dengan Kerajaan Negeri, misalnya melalui Majlis Kewangan Negara dan Majlis Tanah Negara, mengukuhkan sistem persekutuan.",
   salah:{A:"Bidang kuasa Yang di-Pertuan Agong telah termaktub dalam perlembagaan dan bukan faktor pengukuh sistem persekutuan.",B:"Agensi pelaksana menjalankan dasar, bukan faktor yang mengukuhkan hubungan persekutuan-negeri.",D:"Pemusatan kuasa kehakiman dalam badan perundangan bertentangan dengan prinsip pengasingan kuasa."}},

  {n:29,tk:"T5",ms:"91",bab:"Gagasan Malaysia",
   s:"Maklumat berikut berkaitan idea gagasan Malaysia oleh Sir Malcolm MacDonald pada tahun 1951. Apakah rasional cadangan tersebut?",
   stim:"Penggabungan tanah jajahan British di Asia Tenggara bagi membentuk satu entiti politik dan ekonomi.",
   p:{A:"Meneruskan dasar neokolonisasi",B:"Menjayakan rancangan dekolonisasi",C:"Mendapatkan sokongan negara serantau",D:"Menjamin kedudukan pemimpin tempatan"},
   j:"B",
   klu:"Selepas Perang Dunia Kedua, British ingin melepaskan tanah jajahan secara teratur. Apakah istilah bagi proses tersebut?",
   betul:"Cadangan tersebut merupakan sebahagian daripada rancangan dekolonisasi British, iaitu melepaskan tanah jajahan secara terancang dengan menggabungkannya menjadi satu entiti politik dan ekonomi yang lebih mampan.",
   salah:{A:"Tuduhan neokolonialisme merupakan hujah Indonesia menentang Malaysia, bukan rasional cadangan MacDonald.",C:"Sokongan negara serantau bukan tujuan asal cadangan tersebut.",D:"Kedudukan pemimpin tempatan bukan pertimbangan utama British ketika itu."}},

  {n:30,tk:"T5",ms:"103",bab:"Perjanjian Malaysia 1963",
   s:"Apakah perkara dikaitkan dengan Sarawak dan Sabah dalam Perjanjian Malaysia pada 9 Julai 1963?",
   p:{A:"Menetapkan syarat kerakyatan",B:"Menggubal dasar pertahanan",C:"Menentukan hubungan luar",D:"Menubuhkan kabinet sendiri"},
   j:"D",
   klu:"Sabah dan Sarawak diberi hak khas melebihi negeri lain. Apakah kuasa autonomi yang mereka perolehi dalam pentadbiran negeri?",
   betul:"Perjanjian Malaysia memberi Sabah dan Sarawak kuasa autonomi yang khusus, termasuk hak menubuhkan kabinet negeri sendiri bagi mentadbir hal ehwal negeri masing-masing.",
   salah:{A:"Syarat kerakyatan diperuntukkan dalam Perlembagaan Persekutuan.",B:"Pertahanan kekal di bawah bidang kuasa Kerajaan Persekutuan.",C:"Hubungan luar juga terletak di bawah Kerajaan Persekutuan."}},

  {n:31,tk:"T5",ms:"120",bab:"Pemisahan Singapura",
   s:"Maklumat berikut berkaitan ucapan Tunku Abdul Rahman dalam perbahasan di Dewan Rakyat. Bagaimanakah isu tersebut diselesaikan?",
   stim:"Pemisahan Singapura merupakan perkara yang tidak dapat dielakkan.",
   p:{A:"Menganjurkan demonstrasi",B:"Melancarkan konfrontasi",C:"Mengadakan rundingan",D:"Menggunakan pujukan"},
   j:"C",
   klu:"Pemisahan Singapura berlaku secara aman melalui satu dokumen rasmi yang ditandatangani kedua-dua pihak.",
   betul:"Isu tersebut diselesaikan melalui rundingan antara pemimpin Malaysia dan Singapura sehingga termeterainya Perjanjian Pemisahan pada 9 Ogos 1965 secara aman dan teratur.",
   salah:{A:"Demonstrasi bukan kaedah penyelesaian yang diambil oleh kerajaan.",B:"Konfrontasi ialah tindakan Indonesia menentang pembentukan Malaysia, bukan penyelesaian isu Singapura.",D:"Pujukan tidak lagi menjadi pilihan setelah keputusan pemisahan diambil."}},

  {n:32,tk:"T5",ms:"129-130",bab:"Peristiwa 13 Mei 1969",
   s:"Gambar berikut berkaitan rusuhan kaum di negara kita. Apakah usaha kerajaan untuk mengatasi tragedi tersebut?",
   stim:"[Gambar: Peristiwa rusuhan kaum 13 Mei 1969]",
   pilihanTambahan:"I  Melancarkan operasi ketenteraan\nII  Memperkenalkan perang saraf\nIII  Menubuhkan MAGERAN\nIV  Mengisytiharkan darurat",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   j:"D",
   klu:"Selepas 13 Mei, Parlimen digantung dan negara ditadbir oleh sebuah majlis khas. Apakah nama majlis itu?",
   betul:"Kerajaan mengisytiharkan darurat dan menubuhkan Majlis Gerakan Negara (MAGERAN) yang mentadbir negara bagi memulihkan keamanan serta perpaduan selepas tragedi 13 Mei 1969.",
   salah:{A:"Operasi ketenteraan bukan istilah yang digunakan; tentera hanya membantu memulihkan keamanan.",B:"Perang saraf ialah strategi menentang komunis semasa darurat 1948-1960.",C:"Perang saraf tidak berkaitan dengan penyelesaian rusuhan kaum."}},

  {n:33,tk:"T5",ms:"149",bab:"Dewan Bahasa dan Pustaka",
   s:"Dewan Bahasa dan Pustaka (DBP) ditubuhkan pada 22 Jun 1956. Apakah matlamat penubuhannya?",
   p:{A:"Memartabatkan bahasa kebangsaan",B:"Meningkatkan kadar celik huruf",C:"Memupuk minat membaca",D:"Melahirkan penulis muda"},
   j:"A",
   klu:"Perhatikan nama badan ini sendiri. Apakah tugas utamanya terhadap bahasa Melayu selepas kemerdekaan?",
   betul:"DBP ditubuhkan untuk memperkembang, membakukan dan memartabatkan bahasa Melayu sebagai bahasa kebangsaan serta bahasa ilmu dan pentadbiran negara.",
   salah:{B:"Peningkatan kadar celik huruf ialah tanggungjawab sistem pendidikan.",C:"Memupuk minat membaca ialah kesan sampingan usaha penerbitan DBP.",D:"Melahirkan penulis muda merupakan salah satu aktiviti, bukan matlamat utama penubuhan."}},

  {n:34,tk:"T5",ms:"158",bab:"Rukun Negara",
   s:"Maklumat berikut berkaitan matlamat Rukun Negara. Bagaimanakah matlamat tersebut dapat dicapai?",
   stim:"Masyarakat Adil",
   pilihanTambahan:"I  Mempunyai peluang yang sama\nII  Mencipta satu bangsa bersatu\nIII  Mengamalkan kebudayaan yang sesuai\nIV  Membantu pihak yang susah",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   j:"B",
   klu:"Konsep adil bermaksud kekayaan negara dinikmati bersama. Cari dua tindakan yang benar-benar merapatkan jurang antara golongan.",
   betul:"Masyarakat adil tercapai apabila setiap rakyat diberi peluang yang sama untuk maju dan golongan yang susah dibantu supaya jurang sosioekonomi dapat dirapatkan.",
   salah:{A:"Satu bangsa bersatu ialah matlamat Negara Bersatu, bukan Masyarakat Adil.",C:"Pengamalan kebudayaan berkaitan matlamat masyarakat liberal.",D:"Kedua-dua perkara ini merujuk matlamat Rukun Negara yang lain."}},

  {n:35,tk:"T5",ms:"170",bab:"Dasar Ekonomi Baru",
   s:"Maklumat berikut berkaitan usaha kerajaan melaksanakan Dasar Ekonomi Baru (DEB). Bagaimanakah usaha tersebut dilaksanakan?",
   stim:"Penubuhan Lembaga Kemajuan Tanah Persekutuan (FELDA) untuk membantu penduduk di luar bandar.",
   p:{A:"Membuka tanah baharu",B:"Menubuhkan kegiatan koperasi",C:"Menyediakan insentif kewangan",D:"Membuat penyelidikan hasil pertanian"},
   j:"A",
   klu:"Nama FELDA sendiri mengandungi perkataan kemajuan tanah. Apakah yang dilakukan terhadap kawasan hutan untuk peneroka?",
   betul:"FELDA membuka tanah baharu dan menyediakan rancangan penempatan semula bagi peneroka mengusahakan tanaman kelapa sawit dan getah untuk meningkatkan pendapatan mereka.",
   salah:{B:"Kegiatan koperasi diuruskan oleh agensi lain seperti Bank Rakyat dan pergerakan koperasi.",C:"Insentif kewangan bukan kaedah utama pelaksanaan FELDA.",D:"Penyelidikan hasil pertanian dijalankan oleh MARDI, bukan FELDA."}},

  {n:36,tk:"T5",ms:"179",bab:"Pertanian moden",
   s:"Apakah konsep pertanian pintar?",
   p:{A:"Memperluas tanaman komersil",B:"Memperkasa kepakaran petani",C:"Menggunakan teknologi moden",D:"Memelihara kelestarian alam"},
   j:"C",
   klu:"Perkataan pintar dalam istilah moden seperti telefon pintar dan bandar pintar merujuk kepada penggunaan apa?",
   betul:"Pertanian pintar bermaksud penggunaan teknologi moden seperti dron, sensor, automasi dan analisis data bagi meningkatkan hasil serta kecekapan pengeluaran pertanian.",
   salah:{A:"Perluasan tanaman komersil ialah pendekatan tradisional meningkatkan hasil.",B:"Kepakaran petani penting tetapi bukan takrif konsep pertanian pintar.",D:"Kelestarian alam ialah kesan baik pertanian pintar, bukan konsepnya."}},

  {n:37,tk:"T5",ms:"197",bab:"Dasar luar",
   s:"Maklumat berikut berkaitan dasar luar negara kita. Mengapakah Malaysia bertindak demikian?",
   stim:"Malaysia menjalin hubungan dengan Arab Saudi, Mesir dan Yaman.",
   p:{A:"Persekitaran luar",B:"Ikatan sejarah",C:"Keperluan nasional",D:"Kebolehan pemimpin"},
   j:"B",
   klu:"Hubungan dengan negara-negara Asia Barat ini telah wujud sejak berkurun lamanya melalui perdagangan, ilmu dan agama.",
   betul:"Hubungan dengan Arab Saudi, Mesir dan Yaman berasaskan ikatan sejarah yang panjang menerusi perdagangan, penyebaran ilmu dan hubungan keagamaan sejak zaman Kesultanan Melayu.",
   salah:{A:"Persekitaran luar merujuk keadaan politik antarabangsa semasa, bukan sebab hubungan khusus ini.",C:"Keperluan nasional berkaitan kepentingan ekonomi dan keselamatan semasa.",D:"Kebolehan pemimpin ialah faktor pelaksanaan dasar luar, bukan sebab hubungan tersebut terjalin."}},

  {n:38,tk:"T5",ms:"213",bab:"NAM",
   s:"Malaysia telah membangkitkan isu berkaitan Bosnia Herzegovina dalam Sidang Kemuncak NAM di Jakarta, Indonesia pada tahun 1992. Apakah keputusan yang dicapai dalam persidangan tersebut?",
   p:{A:"Menyekat bantuan ketenteraan",B:"Memecat ketua pemimpin Serbia",C:"Menghentikan kerjasama ekonomi",D:"Menggantung keahlian Yugoslavia"},
   j:"D",
   klu:"NAM tidak boleh menghukum sesebuah negara, tetapi boleh mengambil tindakan terhadap status keahliannya sendiri.",
   betul:"Sidang Kemuncak NAM 1992 bersetuju menggantung keahlian Yugoslavia sebagai tindakan protes terhadap keganasan yang berlaku di Bosnia Herzegovina.",
   salah:{A:"NAM tiada kuasa menyekat bantuan ketenteraan negara anggota.",B:"Pemecatan pemimpin sesebuah negara di luar bidang kuasa NAM.",C:"Penghentian kerjasama ekonomi bukan keputusan sidang tersebut."}},

  {n:39,tk:"T5",ms:"231",bab:"Kerjasama serantau",
   s:"Peta berikut berkaitan dengan kerjasama pembangunan wilayah baharu. Apakah manfaat kerjasama tersebut kepada Malaysia?",
   stim:"[Peta: Segi Tiga Pertumbuhan / kerjasama pembangunan wilayah serantau]",
   p:{A:"Mengurangkan monopoli barangan negara maju",B:"Menamatkan tuntutan pertindihan sempadan",C:"Menyekat kemasukan pelabur rantau lain",D:"Mengawal kadar pertukaran mata wang"},
   j:"A",
   klu:"Apabila negara serantau berkongsi pasaran dan sumber, mereka kurang bergantung kepada barangan siapa?",
   betul:"Kerjasama pembangunan wilayah membuka pasaran serantau dan meningkatkan pengeluaran bersama sehingga mengurangkan kebergantungan serta monopoli barangan negara maju.",
   salah:{B:"Isu pertindihan sempadan diselesaikan melalui rundingan atau mahkamah antarabangsa.",C:"Kerjasama serantau menggalakkan pelaburan, bukan menyekatnya.",D:"Kadar pertukaran mata wang dikawal oleh bank pusat, bukan melalui kerjasama wilayah."}},

  {n:40,tk:"T5",ms:"239",bab:"Alam sekitar",
   s:"Berikut merupakan komitmen Malaysia menyertai Sidang Kemuncak Bumi. Apakah kejayaan yang dicapai dalam persidangan tersebut?",
   stim:"2007  \u2014  Persidangan Alam Sekitar di Bali, Indonesia",
   pilihanTambahan:"I  Menggalakkan penggunaan tenaga baharu\nII  Mengawal perkembangan teknologi\nIII  Meningkatkan penggunaan bahan api\nIV  Mengurangkan pembebasan gas rumah hijau",
   p:{A:"I dan II",B:"I dan IV",C:"II dan III",D:"III dan IV"},
   j:"B",
   klu:"Isu utama persidangan alam sekitar ialah pemanasan global. Cari dua tindakan yang mengurangkan pencemaran udara.",
   betul:"Persidangan tersebut menggalakkan penggunaan tenaga baharu yang mesra alam dan menetapkan sasaran mengurangkan pembebasan gas rumah hijau bagi menangani pemanasan global.",
   salah:{A:"Mengawal perkembangan teknologi bukan matlamat persidangan alam sekitar.",C:"Peningkatan penggunaan bahan api fosil bertentangan dengan matlamat persidangan.",D:"Penggunaan bahan api yang meningkat akan menambah pencemaran, bukan mengurangkannya."}}
  ]
};
